### ISSUE TITLE
EncoderHelper 1.4.x 有  1.5 1.6 换成什么了

### ISSUE THREAD

**Issue by weir2010** [yingzhuo/carnival#4]
String token = EncoderHelper.write(cs, "png", response.getOutputStream());  1.4.x  可以用 

1.6  只有 换成什么了，想知道？

**Comment by yingzhuo** [comment]
不好意思啊。 这个项目是我自己一个个人风格很强的东西。 我没想到除了我自己公司的项目外还会有人用到。1.6完全不向下兼容。 

如果你需要的是生成图片验证码，可以参考[https://github.com/yingzhuo/carnival/tree/master/carnival-spring-boot-starter-patchca](https://github.com/yingzhuo/carnival/tree/master/carnival-spring-boot-starter-patchca)。

文档我也没时间整理。 你可能需要阅读源代码来研究到底怎么用。
